services:
  phoenix:
    container_name: phoenix
    build:
      context: ./myapp
    environment:
      - SECRET_KEY_BASE=OUT8Y7R7RwaPFp3dZs1pSX2F0A6fra0glidT7VrmKy5e/GJt5zyMjINHYctrl2ZW # Change this
      - DATABASE_URL=ecto://postgres:example_123@postgres.internal:5432/myapp_prod # Update with your password
      # Dockerfile env
      - PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
      - LC_ALL=en_US.UTF-8
      - MIX_ENV=prod
    ports:
      - 443:4000
    mem_reservation: 2G
  postgres:
    container_name: postgres
    build:
      context: ./postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example_123 # Change this
      - POSTGRES_DB=myapp_prod
      # Dockerfile env
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - PGDATA=/var/lib/postgresql/data/pgdata
      - PG_MAJOR=16
      - PG_VERSION=16.2
      - LANG=en_US.utf8
    mem_reservation: 2G
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver_opts:
      size: 5G # May be adjusted based on your needs
