name: examples/httpserver-java21 (stable)

on:
  workflow_dispatch:

  push:
    branches: [ main ]
    paths:
    - '.github/workflows/example-httpserver-java21-stable.yaml'
    - 'httpserver-java21/**'
    - '!httpserver-java21/README.md'

  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ main ]
    paths:
    - '.github/workflows/example-httpserver-java21-stable.yaml'
    - 'httpserver-java21/**'
    - '!httpserver-java21/README.md'

  schedule:
  - cron: '0 15 * * 1-5'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  UKC_METRO: "https://api.${{ vars.UKC_METRO_STABLE }}.unikraft.cloud/v1"
  UKC_TOKEN: ${{ secrets.UKC_TOKEN }}
  KRAFTKIT_NO_CHECK_UPDATES: true
  KRAFTKIT_LOG_LEVEL: debug

jobs:
  integration:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Test
      id: test
      uses: unikraft/kraftkit@staging
      with:
        run: |
          set -xe;

          cd httpserver-java21;

          kraft cloud deploy \
            --no-start \
            --name httpserver-java21-${GITHUB_RUN_ID} \
            --subdomain httpserver-java21-${GITHUB_RUN_ID} \
            -p 443:8080 \
            -M 1Gi \
            .;

          kraft cloud vm start -w 5s httpserver-java21-${GITHUB_RUN_ID};
          sleep 5;

          curl -Lv --fail-with-body --max-time 10 https://httpserver-java21-${GITHUB_RUN_ID}.${{ vars.UKC_METRO_STABLE }}.unikraft.app

    - name: Cleanup
      uses: unikraft/kraftkit@staging
      if: always()
      with:
        run: |
          set -xe;

          kraft cloud vm stop httpserver-java21-${GITHUB_RUN_ID} || true;
          kraft cloud vm logs httpserver-java21-${GITHUB_RUN_ID} || true;
          kraft cloud vm rm httpserver-java21-${GITHUB_RUN_ID} || true;
          kraft cloud img rm index.unikraft.io/test/httpserver-java21-${GITHUB_RUN_ID} || true;
